# Generated by Django 4.0.5 on 2022-06-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='item_info',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
