# Generated by Django 4.0.5 on 2022-06-15 11:12

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalogitem_item_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='category',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='catalog.category', verbose_name='Категория'),
        ),
    ]
